INSERT INTO topics (id, name)
VALUES (1, 'natural persons'),
(2, 'companies'),
(3, 'property'),
(4, 'contracts'),
(5, 'international sale'),
(6, 'non-contractual obligations'),
(7, 'international carriage'),
(8, 'financial law'),
(9, 'intellectual property rights'),
(10, 'family matters'),
(11, 'inheritance'),
(12, 'recognition and enforcement of foreign decisions'),
(13, 'civil procedure'),
(14, 'international arbitration');